# Supported operations are 'add-layer', 'update-version', 'update-env-variables', 'disable', 'enable'
operation: add-layer

# Layer arn needs to be specified for 'add' or 'update-version' operations
layer_arn: arn:aws:lambda:us-west-2:342994379019:layer:asserts-aws-lambda-layer-py:3

# ASSERTS_METRICSTORE_HOST is required for 'add' operation
ASSERTS_METRICSTORE_HOST: https://chief.tsdb.dev.asserts.ai/api/v1/import/prometheus

# ASSERTS_TENANT and ASSERTS_PASSWORD are optional
ASSERTS_TENANT_NAME: chief
ASSERTS_PASSWORD: wrong
ASSERTS_ENVIRONMENT: dev

# Functions can be specified either through a regex pattern or through a list of function names
# function_name_pattern: Sample.+
function_names:
  - function_py1
