# Supported operations are 'add-layer', 'update-version', 'update-env-variables', 'disable', 'enable'
operation: add-layer

# Layer arn needs to be specified for 'add-layer' or 'update-version' operations
layer_arn: arn:aws:lambda:us-west-2:689200961921:layer:asserts-aws-lambda-layer-python:1

# ASSERTS_METRICSTORE_HOST is required for 'add' operation
ASSERTS_METRICSTORE_HOST: https://chief.tsdb.dev.asserts.ai/api/v1/import/prometheus
# Specify the port if it is different from 443
# ASSERTS_METRICSTORE_PORT: 80

# ASSERTS_TENANT and ASSERTS_PASSWORD are optional
ASSERTS_TENANT_NAME: chief
ASSERTS_PASSWORD: wrong
ASSERTS_ENVIRONMENT: dev
ASSERTS_SITE: dev

# Functions can be specified either through a regex pattern or through a list of function names
# function_name_pattern: Sample.+
function_names:
  - function_py1
