# Supported operations are 'add-layer', 'update-version', 'update-env-variables', 'disable', 'enable'
operation: update-version

# Layer arn needs to be specified for 'add-layer' or 'update-version' operations
layer_arn: arn:aws:lambda:us-west-2:342994379019:layer:asserts-aws-lambda-layer-py:76

# ASSERTS_METRIC_ENDPOINT is required for 'add' operation
ASSERTS_METRIC_ENDPOINT: https://chief.tsdb.dev.asserts.ai/api/v1/import/prometheus

# ASSERTS_TENANT and ASSERTS_PASSWORD are optional
ASSERTS_TENANT_NAME: chief
ASSERTS_PASSWORD: wrong
ASSERTS_ENVIRONMENT: dev
ASSERTS_SITE: dev

ENABLE_TRACING: "true"
OTEL_LOG_LEVEL: debug
OTEL_TRACES_SAMPLER: always_on
OTEL_EXPORTER_OTLP_ENDPOINT: https://Asserts-OTEL-Collector-Latest-1223150161.us-west-2.elb.amazonaws.com:4318

# Functions can be specified either through a regex pattern or through a list of function names
# function_name_pattern: Sample.+
function_names:
  - SampleFunction
